name: cliq
description: "CLIq: Portable and secure SSH and SFTP client."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cliq_terminal:
    path: packages/cliq_terminal
  cliq_ui:
    path: packages/cliq_ui
  lucide_flutter: 0.553.0
  go_router: 17.0.0
  flutter_hooks: 0.21.3+1
  shared_preferences: ^2.5.3
  hooks_riverpod: 3.0.3
  riverpod: ^3.0.3
  logging: ^1.3.0
  drift: ^2.29.0
  drift_flutter: 0.2.7
  path_provider: ^2.1.5
  forui: ^0.16.0
  forui_hooks: ^0.16.0
  dartssh2: ^2.13.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: 2.29.0
  build_runner: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: 2.4.7

flutter:
  uses-material-design: true
