name: cliq
description: "cliq: Portable and secure SSH and SFTP client."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: 3.11.0

workspace:
  - packages/cliq_api
  - packages/cliq_term
  - packages/cliq_ui

dependencies:
  flutter:
    sdk: flutter
  cliq_api:
    path: packages/cliq_api
  cliq_term:
    path: packages/cliq_term
  cliq_ui:
    path: packages/cliq_ui
  dartssh2:
    git:
      url: https://github.com/cliq-ssh/dartssh2.git
      ref: master
  lucide_flutter: 0.563.0
  go_router: 17.1.0
  flutter_hooks: 0.21.3+1
  shared_preferences: 2.5.4
  hooks_riverpod: 3.2.1
  riverpod: 3.2.1
  logging: ^1.3.0
  drift: 2.31.0
  drift_flutter: 0.2.8
  path_provider: ^2.1.5
  forui: 0.18.1
  forui_hooks: 0.17.0
  uuid: ^4.5.2
  simple_icons: ^14.6.1
  url_launcher: ^6.3.2
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: 2.31.0
  build_runner: 2.11.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: 2.4.7

flutter:
  uses-material-design: true

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont_wght.ttf
        - asset: assets/fonts/SourceCodePro-Italic-VariableFont_wght.ttf
          style: italic

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono[wght].ttf
        - asset: assets/fonts/JetBrainsMono-Italic[wght].ttf
          style: italic

