name: CLIq Backend
services:
  keycloak:
    command:
      - start-dev
      - --import-realm
    image: 'quay.io/keycloak/keycloak:26.4.7'
    init: true
    environment:
      TZ: ${TZ}
      # User credentials
      KEYCLOAK_ADMIN: ${ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # Database
      KC_DB_URL_HOST: db
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_USERNAME: ${POSTGRES_USER}

      # Features
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    ports:
      - '127.0.0.1:8100:8080'
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18.1-alpine
    init: true
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  mailpit:
    image: axllent/mailpit:latest
    init: true
    ports:
      - '127.0.0.1:1025:1025'
      - '127.0.0.1:8025:8025'
    environment:
      TZ: ${TZ}
    volumes:
      - mailpit-data:/data
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8025/readyz" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: ~
  mailpit-data: ~
