name: cliq_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.11.1
resolution: workspace

dependencies:
  logging: ^1.3.0
  dio: 5.9.1

dev_dependencies:
  lints: 6.1.0
  test: ^1.25.6
