services:
  node:
    image: node:25.6.0
    user: ${UID:-1000}:${GID:-1000}
    restart: unless-stopped
    command: ["yarn", "start", "--poll", "1000", "--host", "0.0.0.0"]
    working_dir: /app
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
